"""
County Rate Service — provides per-county CMS Medicare Advantage PMPM rates.

Loads the pre-built JSON from `backend/data/cms_county_rates_{year}.json`
(generated by `scripts/import_cms_county_rates.py`).

Fallback chain for member lookups:
  1. ZIP → county mapping (when HUD crosswalk is loaded)
  2. State average (if member has state on file)
  3. National average (CMS_PMPM_BASE from constants.py)
"""

from __future__ import annotations

import json
import logging
import statistics
from pathlib import Path
from typing import Any

from app.constants import CMS_PMPM_BASE

logger = logging.getLogger(__name__)

# Base path for data files
_DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data"

# In-memory cache keyed by year
_rate_cache: dict[int, dict] = {}

# ZIP-to-county-code crosswalk (loaded separately when available)
# Format: {"90210": "05150", ...}  (ZIP → CMS county code)
_zip_to_county: dict[str, str] = {}
_zip_crosswalk_loaded: bool = False


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def _load_year(year: int) -> dict:
    """Load and cache county rate data for a given year."""
    if year in _rate_cache:
        return _rate_cache[year]

    json_path = _DATA_DIR / f"cms_county_rates_{year}.json"
    if not json_path.exists():
        logger.warning("County rate file not found: %s — using national average fallback", json_path)
        _rate_cache[year] = {}
        return {}

    with open(json_path, encoding="utf-8") as f:
        data = json.load(f)

    _rate_cache[year] = data
    county_count = data.get("metadata", {}).get("total_counties", 0)
    logger.info("Loaded %d county rates for year %d", county_count, year)
    return data


def load_zip_crosswalk(path: str | Path | None = None) -> int:
    """
    Load ZIP → CMS county code crosswalk.

    If no path is provided, looks for `backend/data/zip_to_county.json`.
    Returns the number of ZIP codes loaded.

    The crosswalk file should be JSON: {"90210": "05150", ...}
    """
    global _zip_to_county, _zip_crosswalk_loaded

    if path is None:
        # Try the generated crosswalk first, then legacy name
        path = _DATA_DIR / "zip_to_cms_county.json"
        if not path.exists():
            path = _DATA_DIR / "zip_to_county.json"

    path = Path(path)
    if not path.exists():
        logger.info("ZIP-to-county crosswalk not found at %s — will use state/national fallback", path)
        return 0

    with open(path, encoding="utf-8") as f:
        raw = json.load(f)

    # Support both flat format {"zip": "code"} and nested {"zip_to_cms_county": {"zip": "code"}}
    if isinstance(raw, dict) and "zip_to_cms_county" in raw:
        _zip_to_county = raw["zip_to_cms_county"]
    else:
        _zip_to_county = raw

    _zip_crosswalk_loaded = True
    logger.info("Loaded ZIP-to-county crosswalk: %d ZIP codes", len(_zip_to_county))
    return len(_zip_to_county)


# ---------------------------------------------------------------------------
# Rate lookups
# ---------------------------------------------------------------------------

def _bonus_field(bonus_pct: float) -> str:
    """Map bonus percentage to the JSON field name."""
    if bonus_pct >= 5:
        return "rate_5pct_bonus"
    elif bonus_pct >= 3.5:
        return "rate_3_5pct_bonus"
    else:
        return "rate_0pct_bonus"


def get_county_rate(year: int, county_code: str, bonus_pct: float = 0) -> float | None:
    """
    Get the PMPM rate for a specific CMS county code and year.

    Args:
        year: Rate book year (e.g. 2026)
        county_code: CMS 5-digit county code (e.g. "01000")
        bonus_pct: Bonus percentage (0, 3.5, or 5)

    Returns:
        PMPM rate as float, or None if not found.
    """
    data = _load_year(year)
    if not data:
        return None

    rates = data.get("rates_by_county_code", {})
    entry = rates.get(county_code)
    if not entry:
        return None

    field = _bonus_field(bonus_pct)
    return entry.get(field)


def get_state_average(year: int, state: str) -> float | None:
    """Get state-average 0% bonus PMPM for a given state name (uppercased)."""
    data = _load_year(year)
    if not data:
        return None
    return data.get("state_averages", {}).get(state.upper())


def _ensure_crosswalk_loaded() -> None:
    """Auto-load the ZIP crosswalk on first access."""
    if not _zip_crosswalk_loaded:
        load_zip_crosswalk()


def get_county_code_for_zip(zip_code: str) -> str | None:
    """Look up CMS county code from a ZIP code."""
    _ensure_crosswalk_loaded()
    if not _zip_to_county:
        return None
    # Normalize to 5-digit ZIP
    zip5 = (zip_code or "").strip()[:5]
    return _zip_to_county.get(zip5)


def get_member_pmpm(year: int, member: Any, bonus_pct: float = 0) -> float:
    """
    Get the PMPM rate for a member, using the fallback chain:
      1. ZIP → county code → county rate
      2. State → state average rate
      3. National average (CMS_PMPM_BASE)

    The `member` object should have `.zip_code` and optionally `.state` attributes.
    """
    # Try ZIP → county
    zip_code = getattr(member, "zip_code", None)
    if zip_code:
        county_code = get_county_code_for_zip(zip_code)
        if county_code:
            rate = get_county_rate(year, county_code, bonus_pct)
            if rate is not None:
                return rate

    # Try state average
    # Check for state attribute on member, or try to extract from address
    state = getattr(member, "state", None)
    if state:
        avg = get_state_average(year, state)
        if avg is not None:
            return avg

    # Fall back to national average
    return CMS_PMPM_BASE


def get_member_annual_value(year: int, member: Any, raf_score: float, bonus_pct: float = 0) -> float:
    """
    Calculate annual dollar value for a member:
        county_pmpm × 12 × RAF_score

    Falls back gracefully through the ZIP → state → national chain.
    """
    pmpm = get_member_pmpm(year, member, bonus_pct)
    return round(pmpm * 12 * raf_score, 2)


# ---------------------------------------------------------------------------
# Summary / analytics
# ---------------------------------------------------------------------------

def get_rate_summary(year: int) -> dict:
    """
    Returns summary statistics for the year's county rates.

    Includes national stats and per-state breakdowns (min, max, mean, median).
    """
    data = _load_year(year)
    if not data:
        return {"error": "No rate data loaded", "year": year}

    meta = data.get("metadata", {})
    rates = data.get("rates_by_county_code", {})
    state_avgs = data.get("state_averages", {})

    # Per-state breakdown
    state_counties: dict[str, list[float]] = {}
    for entry in rates.values():
        st = entry.get("state", "").upper()
        r = entry.get("rate_0pct_bonus")
        if st and r is not None:
            if st not in state_counties:
                state_counties[st] = []
            state_counties[st].append(r)

    state_summary = {}
    for st, vals in sorted(state_counties.items()):
        state_summary[st] = {
            "county_count": len(vals),
            "min": round(min(vals), 2),
            "max": round(max(vals), 2),
            "mean": round(statistics.mean(vals), 2),
            "median": round(statistics.median(vals), 2),
        }

    return {
        "year": year,
        "total_counties": meta.get("total_counties", len(rates)),
        "national_stats": meta.get("national_stats_0pct", {}),
        "states": state_summary,
    }


def lookup_by_state_county(year: int, state: str, county_name: str, bonus_pct: float = 0) -> dict | None:
    """
    Manual lookup by state name and county name.

    Returns the full rate entry plus the resolved county code, or None.
    """
    data = _load_year(year)
    if not data:
        return None

    key = f"{state.upper()}|{county_name.upper()}"
    code = data.get("rates_by_state_county", {}).get(key)
    if not code:
        return None

    entry = data.get("rates_by_county_code", {}).get(code)
    if not entry:
        return None

    field = _bonus_field(bonus_pct)
    return {
        "county_code": code,
        "state": entry["state"],
        "county": entry["county"],
        "rate": entry.get(field),
        "rate_5pct_bonus": entry.get("rate_5pct_bonus"),
        "rate_3_5pct_bonus": entry.get("rate_3_5pct_bonus"),
        "rate_0pct_bonus": entry.get("rate_0pct_bonus"),
        "rate_esrd": entry.get("rate_esrd"),
    }


# ---------------------------------------------------------------------------
# Convenience: get the PMPM base for a year (national mean from rate data)
# ---------------------------------------------------------------------------

def get_national_mean_pmpm(year: int) -> float:
    """Return the national mean 0% bonus PMPM, or CMS_PMPM_BASE if unavailable."""
    data = _load_year(year)
    if not data:
        return CMS_PMPM_BASE
    return data.get("metadata", {}).get("national_stats_0pct", {}).get("mean", CMS_PMPM_BASE)
