-- Maps AQSoft claims table to Tuva's medical_claim input schema
-- Source: raw.claims (written by Python ingestion pipeline)

with source as (
    select * from {{ source('aqsoft', 'claims') }}
    where claim_type != 'pharmacy'
)

select
    claim_id                                    as claim_id,
    1                                           as claim_line_number,
    case
        when claim_type = 'institutional' then 'institutional'
        else 'professional'
    end                                         as claim_type,
    cast(member_id as varchar)                  as person_id,
    cast(member_id as varchar)                  as member_id,
    null                                        as payer,
    null                                        as plan,
    service_date                                as claim_start_date,
    service_date                                as claim_end_date,
    service_date                                as claim_line_start_date,
    service_date                                as claim_line_end_date,
    case when claim_type = 'institutional'
         then service_date end                  as admission_date,
    case when claim_type = 'institutional'
         and los is not null
         then service_date + cast(los as integer) end as discharge_date,
    null                                        as admit_source_code,
    null                                        as admit_type_code,
    null                                        as discharge_disposition_code,
    pos_code                                    as place_of_service_code,
    null                                        as bill_type_code,
    null                                        as drg_code_type,
    drg_code                                    as drg_code,
    null                                        as revenue_center_code,
    null                                        as service_unit_quantity,
    procedure_code                              as hcpcs_code,
    null                                        as hcpcs_modifier_1,
    null                                        as hcpcs_modifier_2,
    null                                        as hcpcs_modifier_3,
    null                                        as hcpcs_modifier_4,
    null                                        as hcpcs_modifier_5,
    null                                        as rendering_npi,
    billing_tin                                 as rendering_tin,
    billing_npi                                 as billing_npi,
    billing_tin                                 as billing_tin,
    facility_npi                                as facility_npi,
    paid_date                                   as paid_date,
    cast(paid_amount as float)                  as paid_amount,
    cast(allowed_amount as float)               as allowed_amount,
    cast(billed_amount as float)                as charge_amount,
    null                                        as coinsurance_amount,
    null                                        as copayment_amount,
    null                                        as deductible_amount,
    cast(coalesce(paid_amount, allowed_amount, billed_amount) as float) as total_cost_amount,
    'icd-10-cm'                                 as diagnosis_code_type,
    diagnosis_codes[1]                          as diagnosis_code_1,
    diagnosis_codes[2]                          as diagnosis_code_2,
    diagnosis_codes[3]                          as diagnosis_code_3,
    diagnosis_codes[4]                          as diagnosis_code_4,
    diagnosis_codes[5]                          as diagnosis_code_5,
    diagnosis_codes[6]                          as diagnosis_code_6,
    diagnosis_codes[7]                          as diagnosis_code_7,
    diagnosis_codes[8]                          as diagnosis_code_8,
    diagnosis_codes[9]                          as diagnosis_code_9,
    diagnosis_codes[10]                         as diagnosis_code_10,
    null as diagnosis_code_11, null as diagnosis_code_12,
    null as diagnosis_code_13, null as diagnosis_code_14,
    null as diagnosis_code_15, null as diagnosis_code_16,
    null as diagnosis_code_17, null as diagnosis_code_18,
    null as diagnosis_code_19, null as diagnosis_code_20,
    null as diagnosis_code_21, null as diagnosis_code_22,
    null as diagnosis_code_23, null as diagnosis_code_24,
    null as diagnosis_code_25,
    null as diagnosis_poa_1,  null as diagnosis_poa_2,
    null as diagnosis_poa_3,  null as diagnosis_poa_4,
    null as diagnosis_poa_5,  null as diagnosis_poa_6,
    null as diagnosis_poa_7,  null as diagnosis_poa_8,
    null as diagnosis_poa_9,  null as diagnosis_poa_10,
    null as diagnosis_poa_11, null as diagnosis_poa_12,
    null as diagnosis_poa_13, null as diagnosis_poa_14,
    null as diagnosis_poa_15, null as diagnosis_poa_16,
    null as diagnosis_poa_17, null as diagnosis_poa_18,
    null as diagnosis_poa_19, null as diagnosis_poa_20,
    null as diagnosis_poa_21, null as diagnosis_poa_22,
    null as diagnosis_poa_23, null as diagnosis_poa_24,
    null as diagnosis_poa_25,
    null                                        as procedure_code_type,
    null as procedure_code_1,  null as procedure_code_2,
    null as procedure_code_3,  null as procedure_code_4,
    null as procedure_code_5,  null as procedure_code_6,
    null as procedure_code_7,  null as procedure_code_8,
    null as procedure_code_9,  null as procedure_code_10,
    null as procedure_code_11, null as procedure_code_12,
    null as procedure_code_13, null as procedure_code_14,
    null as procedure_code_15, null as procedure_code_16,
    null as procedure_code_17, null as procedure_code_18,
    null as procedure_code_19, null as procedure_code_20,
    null as procedure_code_21, null as procedure_code_22,
    null as procedure_code_23, null as procedure_code_24,
    null as procedure_code_25,
    null as procedure_date_1,  null as procedure_date_2,
    null as procedure_date_3,  null as procedure_date_4,
    null as procedure_date_5,  null as procedure_date_6,
    null as procedure_date_7,  null as procedure_date_8,
    null as procedure_date_9,  null as procedure_date_10,
    null as procedure_date_11, null as procedure_date_12,
    null as procedure_date_13, null as procedure_date_14,
    null as procedure_date_15, null as procedure_date_16,
    null as procedure_date_17, null as procedure_date_18,
    null as procedure_date_19, null as procedure_date_20,
    null as procedure_date_21, null as procedure_date_22,
    null as procedure_date_23, null as procedure_date_24,
    null as procedure_date_25,
    null                                        as in_network_flag,
    'aqsoft'                                    as data_source,
    null                                        as file_name,
    null                                        as file_date,
    current_timestamp                           as ingest_datetime
from source
