-- Maps AQSoft claims table to Tuva's medical_claim input schema
-- Source: raw.claims (written by Python ingestion pipeline)
-- All fields cast to VARCHAR where Tuva expects string types (DuckDB is strict)

with source as (
    select * from {{ source('aqsoft', 'claims') }}
    where claim_type != 'pharmacy'
)

select
    cast(claim_id as varchar)                   as claim_id,
    cast(1 as integer)                          as claim_line_number,
    case
        when claim_type = 'institutional' then 'institutional'
        else 'professional'
    end                                         as claim_type,
    cast(member_id as varchar)                  as person_id,
    cast(member_id as varchar)                  as member_id,
    -- TODO: derive from member plan_type when multi-payer support is added
    cast('medicare' as varchar)                  as payer,
    cast(null as varchar)                       as plan,
    service_date                                as claim_start_date,
    service_date                                as claim_end_date,
    service_date                                as claim_line_start_date,
    service_date                                as claim_line_end_date,
    case when claim_type = 'institutional'
         then service_date end                  as admission_date,
    case when claim_type = 'institutional'
         and los is not null
         then service_date + cast(los as integer) end as discharge_date,
    cast(null as varchar)                       as admit_source_code,
    cast(null as varchar)                       as admit_type_code,
    cast(null as varchar)                       as discharge_disposition_code,
    cast(pos_code as varchar)                   as place_of_service_code,
    cast(null as varchar)                       as bill_type_code,
    cast(null as varchar)                       as drg_code_type,
    cast(drg_code as varchar)                   as drg_code,
    cast(null as varchar)                       as revenue_center_code,
    cast(null as integer)                       as service_unit_quantity,
    cast(procedure_code as varchar)             as hcpcs_code,
    cast(null as varchar)                       as hcpcs_modifier_1,
    cast(null as varchar)                       as hcpcs_modifier_2,
    cast(null as varchar)                       as hcpcs_modifier_3,
    cast(null as varchar)                       as hcpcs_modifier_4,
    cast(null as varchar)                       as hcpcs_modifier_5,
    cast(null as varchar)                       as rendering_npi,
    cast(billing_tin as varchar)                as rendering_tin,
    cast(billing_npi as varchar)                as billing_npi,
    cast(billing_tin as varchar)                as billing_tin,
    cast(facility_npi as varchar)               as facility_npi,
    paid_date                                   as paid_date,
    cast(paid_amount as float)                  as paid_amount,
    cast(allowed_amount as float)               as allowed_amount,
    cast(billed_amount as float)                as charge_amount,
    cast(null as float)                         as coinsurance_amount,
    cast(null as float)                         as copayment_amount,
    cast(null as float)                         as deductible_amount,
    cast(coalesce(paid_amount, allowed_amount, billed_amount) as float) as total_cost_amount,
    'icd-10-cm'                                 as diagnosis_code_type,
    cast(diagnosis_codes[1] as varchar)         as diagnosis_code_1,
    cast(diagnosis_codes[2] as varchar)         as diagnosis_code_2,
    cast(diagnosis_codes[3] as varchar)         as diagnosis_code_3,
    cast(diagnosis_codes[4] as varchar)         as diagnosis_code_4,
    cast(diagnosis_codes[5] as varchar)         as diagnosis_code_5,
    cast(diagnosis_codes[6] as varchar)         as diagnosis_code_6,
    cast(diagnosis_codes[7] as varchar)         as diagnosis_code_7,
    cast(diagnosis_codes[8] as varchar)         as diagnosis_code_8,
    cast(diagnosis_codes[9] as varchar)         as diagnosis_code_9,
    cast(diagnosis_codes[10] as varchar)        as diagnosis_code_10,
    cast(null as varchar) as diagnosis_code_11, cast(null as varchar) as diagnosis_code_12,
    cast(null as varchar) as diagnosis_code_13, cast(null as varchar) as diagnosis_code_14,
    cast(null as varchar) as diagnosis_code_15, cast(null as varchar) as diagnosis_code_16,
    cast(null as varchar) as diagnosis_code_17, cast(null as varchar) as diagnosis_code_18,
    cast(null as varchar) as diagnosis_code_19, cast(null as varchar) as diagnosis_code_20,
    cast(null as varchar) as diagnosis_code_21, cast(null as varchar) as diagnosis_code_22,
    cast(null as varchar) as diagnosis_code_23, cast(null as varchar) as diagnosis_code_24,
    cast(null as varchar) as diagnosis_code_25,
    cast(null as varchar) as diagnosis_poa_1,  cast(null as varchar) as diagnosis_poa_2,
    cast(null as varchar) as diagnosis_poa_3,  cast(null as varchar) as diagnosis_poa_4,
    cast(null as varchar) as diagnosis_poa_5,  cast(null as varchar) as diagnosis_poa_6,
    cast(null as varchar) as diagnosis_poa_7,  cast(null as varchar) as diagnosis_poa_8,
    cast(null as varchar) as diagnosis_poa_9,  cast(null as varchar) as diagnosis_poa_10,
    cast(null as varchar) as diagnosis_poa_11, cast(null as varchar) as diagnosis_poa_12,
    cast(null as varchar) as diagnosis_poa_13, cast(null as varchar) as diagnosis_poa_14,
    cast(null as varchar) as diagnosis_poa_15, cast(null as varchar) as diagnosis_poa_16,
    cast(null as varchar) as diagnosis_poa_17, cast(null as varchar) as diagnosis_poa_18,
    cast(null as varchar) as diagnosis_poa_19, cast(null as varchar) as diagnosis_poa_20,
    cast(null as varchar) as diagnosis_poa_21, cast(null as varchar) as diagnosis_poa_22,
    cast(null as varchar) as diagnosis_poa_23, cast(null as varchar) as diagnosis_poa_24,
    cast(null as varchar) as diagnosis_poa_25,
    cast(null as varchar)                       as procedure_code_type,
    cast(null as varchar) as procedure_code_1,  cast(null as varchar) as procedure_code_2,
    cast(null as varchar) as procedure_code_3,  cast(null as varchar) as procedure_code_4,
    cast(null as varchar) as procedure_code_5,  cast(null as varchar) as procedure_code_6,
    cast(null as varchar) as procedure_code_7,  cast(null as varchar) as procedure_code_8,
    cast(null as varchar) as procedure_code_9,  cast(null as varchar) as procedure_code_10,
    cast(null as varchar) as procedure_code_11, cast(null as varchar) as procedure_code_12,
    cast(null as varchar) as procedure_code_13, cast(null as varchar) as procedure_code_14,
    cast(null as varchar) as procedure_code_15, cast(null as varchar) as procedure_code_16,
    cast(null as varchar) as procedure_code_17, cast(null as varchar) as procedure_code_18,
    cast(null as varchar) as procedure_code_19, cast(null as varchar) as procedure_code_20,
    cast(null as varchar) as procedure_code_21, cast(null as varchar) as procedure_code_22,
    cast(null as varchar) as procedure_code_23, cast(null as varchar) as procedure_code_24,
    cast(null as varchar) as procedure_code_25,
    cast(null as date) as procedure_date_1,  cast(null as date) as procedure_date_2,
    cast(null as date) as procedure_date_3,  cast(null as date) as procedure_date_4,
    cast(null as date) as procedure_date_5,  cast(null as date) as procedure_date_6,
    cast(null as date) as procedure_date_7,  cast(null as date) as procedure_date_8,
    cast(null as date) as procedure_date_9,  cast(null as date) as procedure_date_10,
    cast(null as date) as procedure_date_11, cast(null as date) as procedure_date_12,
    cast(null as date) as procedure_date_13, cast(null as date) as procedure_date_14,
    cast(null as date) as procedure_date_15, cast(null as date) as procedure_date_16,
    cast(null as date) as procedure_date_17, cast(null as date) as procedure_date_18,
    cast(null as date) as procedure_date_19, cast(null as date) as procedure_date_20,
    cast(null as date) as procedure_date_21, cast(null as date) as procedure_date_22,
    cast(null as date) as procedure_date_23, cast(null as date) as procedure_date_24,
    cast(null as date) as procedure_date_25,
    cast(null as integer)                       as in_network_flag,
    'aqsoft'                                    as data_source,
    cast(null as varchar)                       as file_name,
    cast(null as date)                          as file_date,
    current_timestamp                           as ingest_datetime
from source
